# Generated by Django 5.2.3 on 2025-11-03 05:32

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='fotos_animais'),
        ),
    ]
